// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcrepository

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Fixture struct {
	ID       int32       `json:"id"`
	HomeTeam pgtype.Text `json:"home_team"`
	AwayTeam pgtype.Text `json:"away_team"`
}

type FixturePrediction struct {
	ID        int32 `json:"id"`
	FixtureID int32 `json:"fixture_id"`
	UserID    int32 `json:"user_id"`
	PredA     int32 `json:"pred_a"`
	PredB     int32 `json:"pred_b"`
}

type FixtureResult struct {
	FixtureID int32 `json:"fixture_id"`
	ScoreA    int32 `json:"score_a"`
	ScoreB    int32 `json:"score_b"`
}

type User struct {
	ID        int32     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Name      string    `json:"name"`
	ApiKey    string    `json:"api_key"`
}
