// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcrepository

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type QuinielasFixture struct {
	ID       int32       `json:"id"`
	HomeTeam pgtype.Text `json:"home_team"`
	AwayTeam pgtype.Text `json:"away_team"`
}

type QuinielasFixturesResult struct {
	FixtureID int32 `json:"fixture_id"`
	ScoreA    int32 `json:"score_a"`
	ScoreB    int32 `json:"score_b"`
}

type QuinielasResponseFixture struct {
	ID          int32 `json:"id"`
	FixtureID   int32 `json:"fixture_id"`
	UsuarioID   int32 `json:"usuario_id"`
	PrediccionA int32 `json:"prediccion_a"`
	PrediccionB int32 `json:"prediccion_b"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Name      string    `json:"name"`
	ApiKey    string    `json:"api_key"`
}

type Usuario struct {
	ID     int32  `json:"id"`
	Nombre string `json:"nombre"`
}
