// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"time"
)

type User struct {
	ID        []byte
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	ApiKey    string
}
