// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package database

import (
	"context"
)

const createPrediction = `-- name: CreatePrediction :exec
INSERT INTO quinielas_response_fixture (fixture_id, usuario_id, prediccion_a, prediccion_b)
VALUES (?, ?, ?, ?)
`

type CreatePredictionParams struct {
	FixtureID   int32
	UsuarioID   int32
	PrediccionA int32
	PrediccionB int32
}

func (q *Queries) CreatePrediction(ctx context.Context, arg CreatePredictionParams) error {
	_, err := q.db.ExecContext(ctx, createPrediction,
		arg.FixtureID,
		arg.UsuarioID,
		arg.PrediccionA,
		arg.PrediccionB,
	)
	return err
}

const getUserScore = `-- name: GetUserScore :one
SELECT COUNT(*) as total_points
FROM quinielas_response_fixture p
JOIN quinielas_fixtures_result r ON p.fixture_id = r.fixture_id
WHERE p.usuario_id = ?
AND (
    (r.score_a > r.score_b AND p.prediccion_a > p.prediccion_b) OR
    (r.score_a < r.score_b AND p.prediccion_a < p.prediccion_b) OR
    (r.score_a = r.score_b AND p.prediccion_a = p.prediccion_b)
)
`

func (q *Queries) GetUserScore(ctx context.Context, usuarioID int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserScore, usuarioID)
	var total_points int64
	err := row.Scan(&total_points)
	return total_points, err
}
