// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/err": {
            "get": {
                "description": "Returns a JSON error with HTTP 500.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Force error response",
                "responses": {
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/healthz": {
            "get": {
                "description": "Liveness probe; returns status ok when the process is up.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apidoc.HealthResponse"
                        }
                    }
                }
            }
        },
        "/v1/predictions": {
            "post": {
                "description": "Inserts into fixture_predictions; user_id is users.id (integer) from POST /v1/users.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "predictions"
                ],
                "summary": "Submit prediction",
                "parameters": [
                    {
                        "description": "Prediction payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apidoc.PostPredictionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "plain text error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "plain text error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/users": {
            "post": {
                "description": "Creates a row in the users table.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Register user",
                "parameters": [
                    {
                        "description": "User payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apidoc.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/apidoc.CreateUserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apidoc.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/users/{userID}/score": {
            "get": {
                "description": "Aggregates matching predictions against stored fixture results.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "predictions"
                ],
                "summary": "User prediction score",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "users.id (integer)",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apidoc.UserScoreResponse"
                        }
                    },
                    "400": {
                        "description": "plain text error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "plain text error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "apidoc.CreateUserRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "apidoc.CreateUserResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "apidoc.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "apidoc.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "apidoc.PostPredictionRequest": {
            "type": "object",
            "properties": {
                "fixture_id": {
                    "type": "integer"
                },
                "pred_a": {
                    "type": "integer"
                },
                "pred_b": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "apidoc.UserScoreResponse": {
            "type": "object",
            "properties": {
                "total_points": {
                    "type": "integer"
                }
            }
        }
    },
    "tags": [
        {
            "description": "Liveness and error test routes",
            "name": "health"
        },
        {
            "description": "User registration",
            "name": "users"
        },
        {
            "description": "Quiniela predictions and scores",
            "name": "predictions"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Quiniela API",
	Description:      "HTTP API for users, predictions, and health checks. Set DB_URL (Postgres). Optional SWAGGER_HOST for Swagger UI \"Try it out\" (defaults to localhost:PORT).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
